FROM node:12-alpine AS builder
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .

RUN npm run build

FROM builder AS local
CMD ["npm", "run", "start"]

FROM builder AS ci
CMD ["npm", "run", "test"]

FROM builder AS cd
CMD ["npm", "run", "serve"]
