version: "3.7"

####################### Services Definition #######################
services:
  server:
    image: server:local
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
      target: cd
    volumes:
      - "./:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - 5000:5000
    environment:
      - PORT=5000
      - JWT_SECRET=mysecret
    networks:
      - default

####################### Networks Definition #######################
networks:
  default:
    driver: bridge
