# Compose runtime environment variables
x-server-variables: &server-variables
  IN_COMPOSE: "true"
  JWT_SECRET: "PrettyShittySecret"
  DATABASE_HOST: "database"
  DATABASE_PORT: 5432
  DATABASE_USERNAME: "admin"
  DATABASE_PASSWORD: "password"
  DATABASE_NAME: "test"

x-database-variables: &database-variables
  POSTGRES_MULTIPLE_DATABASES: "dev,test,prod"
  POSTGRES_USER: "admin"
  POSTGRES_PASSWORD: "password"

# Extended Services Definition
services:
  server:
    image: ${COMPOSE_PROJECT_NAME}_server:ci
    build:
      dockerfile: docker/Dockerfile-server.ci
    ports:
      - "7001:7001"
    environment:
      <<: *server-variables

  database:
    image: ${COMPOSE_PROJECT_NAME}_database:ci
    build:
      dockerfile: docker/Dockerfile-database.ci
    ports:
      - "5435:5432"
    environment:
      <<: *database-variables
