steps:
  #################################################################
  # Build
  #################################################################
  - id: "build"
    name: "docker/compose:1.29.2"
    args: [
      "build",
      "server"
    ]
    env:
      - "COMPOSE_FILE=docker/docker-compose.yml:docker/docker-compose.cd.yml"
      - "COMPOSE_PROJECT_NAME=backend-booster-graphql-postgresql"

  #################################################################
  # Tag
  #################################################################
  - id: "tag-1"
    name: "gcr.io/cloud-builders/docker"
    args: [
      "tag",
      "backend-booster-graphql-postgresql_server:cd",
      "gcr.io/$PROJECT_ID/server:$SHORT_SHA"
    ]

  - id: "tag-2"
    name: "gcr.io/cloud-builders/docker"
    args: [
      "tag",
      "backend-booster-graphql-postgresql_server:cd",
      "gcr.io/$PROJECT_ID/server:development"
    ]

  #################################################################
  # Push
  #################################################################
  - id: "push"
    name: "gcr.io/cloud-builders/docker"
    args: [
      "push",
      "gcr.io/$PROJECT_ID/server"
    ]

  #################################################################
  # Migrate
  #################################################################
  - id: "migrate"
    name: "gcr.io/google-appengine/exec-wrapper"
    args: [
      "-i", "gcr.io/$PROJECT_ID/server:development",
      "-s", "$PROJECT_ID:us-central1:development",
      "-e", "IN_GOOGLE_CLOUD=true",
      "-e", "DATABASE_HOST=${_DATABASE_HOST}",
      "-e", "DATABASE_USERNAME=${_DATABASE_USERNAME}",
      "-e", "DATABASE_PASSWORD=${_DATABASE_PASSWORD}",
      "-e", "DATABASE_NAME=${_DATABASE_NAME}",
      "--", "npm", "run", "db:migrate:up"
    ]

  #################################################################
  # Deploy
  #################################################################
  - id: "deploy"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args: [
      "run", "deploy", "server-development",
      "--allow-unauthenticated",
      "--platform", "managed",
      "--region", "us-central1",
      "--add-cloudsql-instances", "development",
      "--image", "gcr.io/$PROJECT_ID/server:development",
      "--set-env-vars", "IN_GOOGLE_CLOUD=true",
      "--set-env-vars", "JWT_SECRET=${_JWT_SECRET}",
      "--set-env-vars", "DATABASE_HOST=${_DATABASE_HOST}",
      "--set-env-vars", "DATABASE_USERNAME=${_DATABASE_USERNAME}",
      "--set-env-vars", "DATABASE_PASSWORD=${_DATABASE_PASSWORD}",
      "--set-env-vars", "DATABASE_NAME=${_DATABASE_NAME}"
    ]
